export const products = [
  {
    id: "1",
    name: "2024 Anti-Virus Bitdefender Latest Version",
    brand: "Bitdefender",
    description: "An anti-virus software",
    price: "150.00",
    oldPrice: "300.00",
    categories: ["Software", "Security"],
  },
  {
    id: "2",
    name: "Microsoft Office 2016",
    brand: "Microsoft",
    description:
      "Microsoft Office 2016 is a powerful software suite from Microsoft, including Word, Excel, PowerPoint, and more.",
    price: "299.00",
    oldPrice: "400.00",
    categories: ["Software", "Productivity"],
  },
  {
    id: "3",
    name: "Adobe Photoshop CC 2024",
    brand: "Adobe",
    description: "A powerful image editing and graphic design software.",
    price: "250.00",
    oldPrice: "350.00",
    categories: ["Software", "Design"],
  },
  {
    id: "4",
    name: "Norton AntiVirus Plus 2024",
    brand: "Norton",
    description:
      "Protect your PC from viruses, malware, spyware, and ransomware.",
    price: "100.00",
    oldPrice: "200.00",
    categories: ["Software", "Security"],
  },
  {
    id: "5",
    name: "Autodesk AutoCAD 2024",
    brand: "Autodesk",
    description:
      "Design and shape the world around you with the powerful, connected design tools in Autodesk AutoCAD software.",
    price: "1200.00",
    oldPrice: "1500.00",
    categories: ["Software", "Design"],
  },
  {
    id: "6",
    name: "Microsoft Windows 11 Pro",
    brand: "Microsoft",
    description:
      "The latest version of the Microsoft Windows operating system.",
    price: "199.00",
    oldPrice: "299.00",
    categories: ["Software", "Operating System"],
  },
  {
    id: "7",
    name: "CorelDRAW Graphics Suite 2024",
    brand: "Corel",
    description:
      "Graphic design software for vector illustration, layout, photo editing, and more.",
    price: "499.00",
    oldPrice: "699.00",
    categories: ["Software", "Design"],
  },
  {
    id: "8",
    name: "Kaspersky Internet Security 2024",
    brand: "Kaspersky",
    description:
      "Advanced protection against viruses, malware, and online threats.",
    price: "80.00",
    oldPrice: "160.00",
    categories: ["Software", "Security"],
  },
  {
    id: "9",
    name: "Intuit QuickBooks 2024",
    brand: "Intuit",
    description: "Accounting software for small businesses.",
    price: "300.00",
    oldPrice: "450.00",
    categories: ["Software", "Business"],
  },
  {
    id: "10",
    name: "McAfee Total Protection 2024",
    brand: "McAfee",
    description: "Comprehensive protection for your digital life.",
    price: "90.00",
    oldPrice: "180.00",
    categories: ["Software", "Security"],
  },
  {
    id: "11",
    name: "Slack Premium",
    brand: "Slack",
    description:
      "A collaboration hub that connects your work with the people you work with.",
    price: "12.50",
    oldPrice: "15.00",
    categories: ["Software", "Communication"],
  },
  {
    id: "12",
    name: "Zoom Pro",
    brand: "Zoom",
    description:
      "Video conferencing software with real-time messaging and content sharing.",
    price: "14.99",
    oldPrice: "19.99",
    categories: ["Software", "Communication"],
  },
  {
    id: "13",
    name: "VMware Workstation Pro 2024",
    brand: "VMware",
    description:
      "Run multiple operating systems as virtual machines (VMs) on a single Windows or Linux PC.",
    price: "250.00",
    oldPrice: "300.00",
    categories: ["Software", "Virtualization"],
  },
  {
    id: "14",
    name: "Dropbox Business",
    brand: "Dropbox",
    description: "A secure file sharing and storage solution for your team.",
    price: "20.00",
    oldPrice: "25.00",
    categories: ["Software", "Storage"],
  },
  {
    id: "15",
    name: "Spotify Premium",
    brand: "Spotify",
    description: "Premium music streaming service.",
    price: "9.99",
    oldPrice: "12.99",
    categories: ["Software", "Entertainment"],
  },
];
